name: DevelopmentPreview
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Install project dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Show VERCEL_TOKEN variable
        run: echo ${{ secrets.VERCEL_TOKEN }}
      - name: DeployToVercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --yes

#name: GitHub Actions Vercel Preview Deployment
#env:
#  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
#on:
#  push:
#    branches-ignore:
#      - main
#jobs:
#  Deploy-Preview:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Install Vercel CLI
#        run: npm install --global vercel@canary
#      - name: Pull Vercel Environment Information
#        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Build Project Artifacts
#        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
#      - name: Deploy Project Artifacts to Vercel
#        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
