name: DevelopmentPreview

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Install project dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: DeployToVercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod
