name: Deploy Templater front-end App
on: push
jobs:
  myFirstEchoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm run test
    link: